<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>x.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="GTCUI" Version="1.0.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="17.14.249" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <!-- Disabling PublishPlayer target to prevent compilation delays since UdemyPlayer is already compiled and cached on disk -->
  <!--
  <Target Name="PublishPlayer" BeforeTargets="PrepareForBuild">
    <MSBuild Projects="..\UdemyPlayer\UdemyPlayer.csproj" Targets="Publish" Properties="Configuration=$(Configuration);Platform=AnyCPU" />
  </Target>
  -->

  <ItemGroup>
    <EmbeddedResource Include="..\UdemyPlayer\bin\$(Configuration)\net5.0-windows\win-x64\publish\UdemyPlayer.exe" Link="Resources\UdemyPlayer.exe" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Engine\*.exe" />
    <EmbeddedResource Include="cookie-scoop.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Extension\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="..\UdemyPlayer\bin\Debug\net5.0-windows\win-x64\publish\UdemyPlayer.exe" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\fetchpik.com-gif-RqWLIJX7la.gif" />
  </ItemGroup>

  <ItemGroup>
	  <Resource Include="Telegram_logo.svg.png" />
	  <Resource Include="Views\fetchpik.com-gif-RqWLIJX7la.gif" />
	  <Resource Include="yhwach.png" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="cdm_worker.py" />
    <None Remove="wvd.dat" />
  </ItemGroup>

</Project>
